# Generated by Django 4.1.5 on 2023-07-14 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nazm',
            name='date_written',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 42, 3, 567163)),
        ),
    ]
