# Generated by Django 4.1.5 on 2023-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazm', '0003_alter_nazm_date_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nazm',
            name='date_written',
            field=models.DateTimeField(),
        ),
    ]
